# Generated by Django 3.0.8 on 2020-07-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('kpp', models.SmallIntegerField(choices=[[0, 'Механическая коробка передач'], [1, 'Автоматическая коробка передач'], [2, 'Роботизированная коробка передач']])),
                ('color', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
